databases:
  - name: test_render_db_production
    databaseName: test_render_db_production
    user: test_render_user
    region: singapore

services:
  - type: web
    name: test_render_db_production
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: render_app
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false
    autoDeploy: false