databases:
  - name: test_render
    databaseName: test_render_db_production
    user: test_render_user
    region: singapore

services:
  - type: web
    name: test_render
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: test_render
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    autoDeploy: false